name: Compile and Publish Resume & Cover Letter

on:
  push:
    branches: [ master ]
    paths:
      - 'resume/**.md'
      - 'cover-letter/coverletter.md'
      - 'templates/resume-template.tex'
      - 'templates/coverletter-template.tex'
      - '.github/workflows/workflow.yml'
      - 'Makefile'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install minimal TeX dependencies and Microsoft fonts
      run: |
        sudo apt-get update
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra pandoc ttf-mscorefonts-installer
        sudo fc-cache -f -v

    - name: Install Fonts
      run: |
        mkdir -p ~/.local/share/fonts
        cp ./assets/fonts/**/*.ttf ~/.local/share/fonts/
        fc-cache -f -v

    - name: Compile resume and cover letter
      run: make

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add GitHub to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout storage repository
      uses: actions/checkout@v3
      with:
        repository: pewriebontal/storage
        path: storage-repo
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Create directories if needed
      run: |
        mkdir -p storage-repo/public/pdfs

    - name: Copy files to storage repository
      run: |
        cp out/* storage-repo/public/pdfs/

    - name: Commit and push changes
      run: |
        cd storage-repo
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add public/pdfs/*
        git commit -m "Update resume and cover letter to latest version [ci skip]" || echo "No changes to commit"
        git push